services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    command: postgres -c listen_addresses='*'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:

networks:
  postgres-network:
    driver: bridge