version: '3.8'

services:
  server:
    restart: always
    build:
      context: /services/webserver/Monkey-Factory
      dockerfile: Dockerfile

  spinning_planet:
    restart: always
    build:
      context: /services/webserver/SpacePortfolio
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production

  vertical_profile:
    restart: always
    build:
      context: /services/webserver/vertical_profile
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production

  wave_collapse:
    restart: always
    build:
      context: /services/webserver/WaveCollapseEditor
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  postgress:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  caddy_data:
  caddy_config:
  pg-data:
