version: '3.8'

services:
  server:
    build:
      context: /services/webserver/Monkey-Factory
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
 
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: